name: Run Prakiraan Cuaca

on:
  workflow_dispatch:
  schedule:
    - cron: '7 9 * * *'  # Setiap hari jam 05:00 WIB
    - cron: '9 9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests pandas pillow

      - name: Run script
        run: python main.py
